version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: taskflow_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: taskflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ➕ A sua API conectada perfeitamente ao seu banco atual:
  web:
    build: .
    container_name: taskflow_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      # Usando 'db' (nome do serviço) e as suas credenciais exatas: admin e taskflow_db
      DATABASE_URL: postgresql://postgres:admin@db:5432/taskflow_db
    depends_on:
      - db

volumes:
  postgres_data: